# Define o estágio da pipeline como 'deploy'
pages:
  stage: deploy
  # Define o script que será executado
  script:
    # Cria um diretório 'public'
    - mkdir .public
    # Copia todos os arquivos do diretório raiz para o diretório 'public'
    - cp -r * .public
    # Move o diretório 'public' para o diretório raiz do projeto
    - mv .public public
  # Define os artefatos que serão gerados pela pipeline
  artifacts:
    paths:
      # O diretório 'public' será o artefato que o GitLab Pages usará
      - public
  # Define que este trabalho só será executado no branch 'main' (ou 'master')
  only:
    - main
